name: Bonsai CLI
description: WordPress CLI tool for generating and managing reusable components
version: 0.0.1

components:
  - hero
  - header
  - card

sections:
  site_header:
    component: header
    data:
      siteName: "Bonsai"
      iconComponent: "heroicon-o-command-line"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#commands", "label": "Commands"},
        {"url": "#docs", "label": "Documentation"}
      ]
      primaryLink: "https://github.com/jackalopelabs/bonsai-cli"
      containerClasses: "max-w-5xl mx-auto"
      containerInnerClasses: "px-6"
  
  home_hero:
    component: hero
    data:
      title: "Bonsai-CLI"
      subtitle: "WordPress Component Management"
      description: "A WordPress CLI tool for generating and managing reusable components in Roots-based projects"
      imagePaths: ["https://placehold.co/600x400/png"]
      buttonText: "Get Started"
      buttonLink: "#installation"
      secondaryText: "View Docs"
      secondaryLink: "#documentation"
      buttonLinkIcon: true
      secondaryIcon: true
      iconMappings:
        dropdownIcon: "heroicon-s-chevron-down"
        buttonLinkIcon: "heroicon-s-arrow-down-tray"
        secondaryIcon: "heroicon-s-arrow-right"
  
  services_card:
    component: card
    data:
      sectionId: "services"
      sectionTitle: "<span class=\"hidden sm:inline\">Our</span> Services"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#docs", "label": "Documentation"}
      ]
      featureItems: [
        {
          "icon": "heroicon-o-command-line",
          "title": "Component Generation",
          "description": "Generate reusable components with a single command."
        },
        {
          "icon": "heroicon-o-puzzle-piece",
          "title": "Section Builder",
          "description": "Create and manage page sections with dynamic data."
        },
        {
          "icon": "heroicon-o-template",
          "title": "Template System",
          "description": "Pre-built templates for rapid WordPress development."
        }
      ]

layouts:
  bonsai:
    sections:
      - site_header
      - home_hero
      - services_card

pages:
  home:
    title: "Bonsai CLI"
    layout: bonsai
    is_homepage: true

# WordPress specific configurations
wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    
  image_sizes:
    hero_image:
      width: 1920
      height: 1080
      crop: true

# Asset compilation settings
assets:
  styles:
    - resources/styles/bonsai.scss
  scripts:
    - resources/scripts/bonsai.js