name: Bonsai CLI
description: WordPress CLI tool for generating and managing reusable components
version: 0.0.1

# Define required components
components:
  - hero
  - header
  - card

# Define sections with component mappings and data
sections:
  site_header:
    component: header
    data:
      siteName: "🌳 Bonsai CLI"
      iconComponent: "heroicon-o-command-line"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#commands", "label": "Commands"},
        {"url": "#docs", "label": "Documentation"}
      ]
      ctaButton:
        text: "View on GitHub"
        url: "https://github.com/jackalopelabs/bonsai-cli"
        classes: "btn btn-primary"
      containerClasses: "container mx-auto px-4"
  
  home_hero:
    component: hero
    data:
      title: "🌳 Bonsai CLI"
      subtitle: "WordPress Component Management"
      description: "Build beautiful, component-based WordPress sites faster than ever"
      images:
        - path: "/images/hero-main.jpg"
          alt: "Bonsai CLI Demo"
      buttons:
        primary:
          text: "Get Started"
          url: "#installation"
          icon: "heroicon-s-arrow-down-tray"
        secondary:
          text: "View Docs"
          url: "#documentation"
          icon: "heroicon-s-book-open"
      classes:
        wrapper: "py-20 bg-gradient-to-r from-emerald-600 to-green-500"
        content: "container mx-auto px-4"
  
  features_card:
    component: card
    data:
      sectionId: "features"
      sectionTitle: "Features"
      navLinks: [
        {"url": "#commands", "label": "Commands"},
        {"url": "#docs", "label": "Documentation"}
      ]
      featureItems: [
        {
          "icon": "heroicon-o-command-line",
          "title": "Component Generation",
          "description": "Generate reusable components with a single command."
        },
        {
          "icon": "heroicon-o-puzzle-piece",
          "title": "Section Builder",
          "description": "Create and manage page sections with dynamic data."
        },
        {
          "icon": "heroicon-o-template",
          "title": "Template System",
          "description": "Pre-built templates for rapid WordPress development."
        }
      ]

# Define layouts that combine sections
layouts:
  bonsai_main:
    sections:
      - site_header
      - home_hero
      - features_card

# Define WordPress pages
pages:
  home:
    title: "Home | Bonsai CLI"
    layout: bonsai_main
    template: front-page
    meta:
      _wp_page_template: templates/template-bonsai.blade.php
    is_homepage: true

# WordPress specific configurations
wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    
  image_sizes:
    hero_image:
      width: 1920
      height: 1080
      crop: true

# Asset compilation settings
assets:
  styles:
    - resources/styles/bonsai.scss
  scripts:
    - resources/scripts/bonsai.js