name: Bonsai CLI
description: WordPress CLI tool for generating and managing reusable components
version: 0.0.1

# Add theme settings at the top level
theme:
  body:
    class: 'bg-gray-100'

# ASCII art configuration section
ascii_art:
  default: |
    ${green}                    &
                          && & &
                        & &&&&&~&
                         &  &&&&
                          &&&~|\
                           &//~
                          |/
                         /|\
               &&       |//~
                 &&    \_/     && & &
          &&&    &&     //_/  /&&&/_&&&
           &&&__&&   \_\_\/~/   &&&
         & &\&  &&&&\|&  /~|     &
          &&& & &    /~~
                   ${brown}:___________./~~~\.___:
                    \                     /
                     \_________________/
                     (_)           (_)${reset}

components:
  - hero
  - header
  - card
  - widget
  - pricing-box
  - feature-grid

sections:
  site_header:
    component: header
    data:
      siteName: "Bonsai"
      iconComponent: "heroicon-o-command-line"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#commands", "label": "Commands"},
        {"url": "#docs", "label": "Documentation"}
      ]
      primaryLink: "https://github.com/jackalopelabs/bonsai-cli"
      containerClasses: "max-w-5xl mx-auto"
      containerInnerClasses: "px-6"
      headerClass: "bg-indigo-500 bg-opacity-60 backdrop-blur-md shadow-lg border border-transparent rounded-full mx-auto p-1 my-4"
      # Add icon classes
      iconClasses: "h-8 w-8 mr-2 p-1"
      chevronClasses: "w-4 h-4 ml-2 inline-block"
      buttonText: "Plans"
      buttonPrefix: "See"
  
  home_hero:
    component: hero
    data:
      # Content
      title: "Your Hero Title"
      subtitle: "Your subtitle here"
      description: "Your description text"
      buttonText: "Get Started"
      buttonLink: "#"
      secondaryText: "Learn More"
      secondaryLink: "#"
      
      # Style Classes
      containerClasses: "container mx-auto px-4 mb-12 mt-0 md:mt-24"
      columnClasses: "flex flex-col md:flex-row items-center md:items-start -mx-4"
      imageColumnClasses: "w-full md:w-1/2 px-4 flex justify-center items-center mt-12 md:mt-0 md:order-last"
      textColumnClasses: "w-full md:w-1/2 px-4"
      titleClass: "font-semibold text-6xl"
      productTagClasses: "bg-white bg-opacity-50 px-3 py-1 text-sm inline-block"
      productIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      buttonClasses: "bg-gradient-to-r from-indigo-500 to-blue-600 text-white text-xl py-2 px-5 rounded-full"
      buttonIconClasses: "text-white w-6 h-6 ml-2 inline-block align-middle"
      secondaryClasses: "text-sm bg-transparent px-2 py-1 backdrop-blur-md shadow-lg rounded-md border border-gray-100"
      secondaryIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      
      # Icons
      iconMappings:
        dropdownIcon: "heroicon-s-chevron-down"
        buttonLinkIcon: "heroicon-s-shopping-cart"
        secondaryIcon: "heroicon-s-chevron-right"
  
  services_card:
    component: card
    data:
      sectionId: "services"
      sectionTitle: "<span class=\"hidden sm:inline\">Our</span> Services"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#docs", "label": "Documentation"}
      ]
      # Style classes
      sectionClasses: "py-12"
      containerClasses: "max-w-4xl mx-auto px-6"
      navContainerClasses: "flex flex-col sm:flex-row flex-wrap items-start mb-6 justify-center md:justify-center"
      titleClasses: "text-lg text-gray-700 bg-white p-3 rounded-lg mr-4 mb-4 sm:mb-0"
      titleIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      navLinkClasses: "text-lg text-gray-700 p-3 mb-4 sm:mb-0 hidden sm:inline"
      navLinkIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      # Card styles
      cardContainerClasses: "bg-white bg-opacity-50 grid md:grid-cols-2 gap-8 rounded-3xl p-3"
      imageColumnClasses: "md:w-1/2 mx-auto"
      featuresColumnClasses: "md:w-2/2 space-y-6"
      featureItemClasses: "flex items-start space-x-4 bg-white rounded-xl p-3"
      featureIconClasses: "h-6 w-6 text-indigo-500"
      featureTitleClasses: "text-lg font-semibold"
      featureDescriptionClasses: "text-sm text-gray-500"
      featureItems: [
        {
          "icon": "heroicon-o-command-line",
          "title": "Component Generation",
          "description": "Generate reusable components with a single command."
        },
        {
          "icon": "heroicon-o-puzzle-piece",
          "title": "Section Builder",
          "description": "Create and manage page sections with dynamic data."
        },
        {
          "icon": "heroicon-o-template",
          "title": "Template System",
          "description": "Pre-built templates for rapid WordPress development."
        }
      ]

  features_widget:
    component: widget
    data:
      items:
        - id: "widget-1"
          title: "Component Generation"
          icon: "heroicon-o-command-line"
          content: ""
          cta:
            title: "Component Generation"
            link: "#components"
            imagePath: "https://placehold.co/600x400/png"
            buttonText: "Learn more"
            # CTA style configurations
            containerClasses: "cta bg-white bg-opacity-50 rounded-lg flex items-center space-x-8 mt-2"
            imageClasses: "w-44 h-44 object-cover rounded-xl"
            contentContainerClasses: "flex items-center justify-between flex-1"
            titleClasses: "text-xl font-semibold"
            buttonClasses: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
            buttonIconClasses: "w-4 h-4 ml-2"
          description: "Generate and manage reusable components with ease:"
          listItems:
            - number: 1
              itemName: "Quick Setup"
              text: "Initialize your project with bonsai:init"
            - number: 2
              itemName: "Component Library"
              text: "Access pre-built components ready for customization"
            - number: 3
              itemName: "Custom Components"
              text: "Create your own components with simple commands"

        - id: "widget-2"
          title: "Section Builder"
          icon: "heroicon-o-puzzle-piece"
          content: ""
          cta:
            title: "Section Builder"
            link: "#sections"
            imagePath: "https://placehold.co/600x400/png"
          description: "Build dynamic page sections with powerful features:"
          listItems:
            - number: 1
              itemName: "Dynamic Data"
              text: "Configure sections using YAML files"
            - number: 2
              itemName: "Reusable Sections"
              text: "Create once, use anywhere in your site"
            - number: 3
              itemName: "Flexible Layout"
              text: "Combine sections into custom page layouts"

        - id: "widget-3"
          title: "Template System"
          icon: "heroicon-o-template"
          content: ""
          cta:
            title: "Template System"
            link: "#templates"
            imagePath: "https://placehold.co/600x400/png"
          description: "Generate complete WordPress sites from templates:"
          listItems:
            - number: 1
              itemName: "Pre-built Templates"
              text: "Start with our collection of ready-to-use templates"
            - number: 2
              itemName: "Custom Templates"
              text: "Create your own templates for reuse"
            - number: 3
              itemName: "WordPress Integration"
              text: "Seamlessly works with WordPress and Sage"

      # Accordion style configurations
      accordionClasses: "flex items-center space-x-2 cursor-pointer px-3"
      activeAccordionClasses: "bg-white bg-opacity-50 rounded-xl p-3"
      containerClasses: "my-4"
      iconContainerClasses: "h-10 w-10 flex items-center justify-center mr-2"
      activeIconContainerClasses: "bg-gradient-to-r from-emerald-600 to-green-500 rounded-full"
      inactiveIconContainerClasses: "bg-white rounded-full"
      iconClasses: "inline-block h-4 w-4"
      activeIconClasses: "text-white"
      inactiveIconClasses: "text-gray-700"
      titleClasses: "font-bold"
      contentClasses: "text-gray-400"
      contentWrapperClasses: "flex-1"
      iconPaths:
        template: "M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z"
        command-line: "M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
        puzzle-piece: "M11 4a2 2 0 114 0v1a1 1 0 001 1h3a1 1 0 011 1v3a1 1 0 01-1 1h-1a2 2 0 100 4h1a1 1 0 011 1v3a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a2 2 0 10-4 0v1a1 1 0 01-1 1H7a1 1 0 01-1-1v-3a1 1 0 00-1-1H4a2 2 0 110-4h1a1 1 0 001-1V7a1 1 0 011-1h3a1 1 0 001-1V4z"

  pricing:
    component: pricing-box
    data:
      title: "Choose Your Plan"
      subtitle: "Limited-time pricing available now"
      description: "Select the plan that best suits your needs. Lock in your price early and keep it forever, or until you cancel."
      pricingBoxes: [
        {
          "icon": "heroicon-o-command-line",
          "iconColor": "text-gray-400",
          "planType": "Basic",
          "price": "Free",
          "features": [
            "Generate components",
            "Basic templates",
            "Documentation access"
          ],
          "ctaLink": "#get-started",
          "ctaText": "Get Started",
          "ctaColor": "bg-white",
          "iconBtn": "heroicon-o-arrow-right",
          "iconBtnColor": "text-gray-500"
        },
        {
          "icon": "heroicon-o-puzzle-piece",
          "iconColor": "text-gray-500",
          "planType": "Pro",
          "price": "$99<span class=\"text-xs text-gray-400\">/yr</span>",
          "features": [
            "All Basic features",
            "Custom components",
            "Advanced templates",
            "Priority support",
            "Early access"
          ],
          "ctaLink": "#buy-pro",
          "ctaText": "Buy Now",
          "ctaColor": "bg-gradient-to-r from-emerald-600 to-green-500 text-white",
          "iconBtn": "heroicon-o-shopping-cart",
          "iconBtnColor": "text-white"
        },
        {
          "icon": "heroicon-o-star",
          "iconColor": "text-yellow-500",
          "planType": "Sensei",
          "price": "$249<span class=\"text-xs text-gray-400\">/yr</span>",
          "features": [
            "All Pro features",
            "Custom development",
            "Private Slack channel",
            "1-on-1 mentoring",
            "Early beta access",
            "Custom integrations",
            "Architecture review"
          ],
          "ctaLink": "#buy-sensei",
          "ctaText": "Buy Now",
          "ctaColor": "bg-gradient-to-r from-yellow-500 to-amber-500 text-white",
          "iconBtn": "heroicon-o-shopping-cart",
          "iconBtnColor": "text-white"
        }
      ]

  feature_grid:
    component: feature-grid
    data:
      sectionTitle: "Features"
      subtitle: "Everything you need to build amazing WordPress sites"
      # Style configurations
      sectionClasses: "py-24 bg-gray-50"
      containerClasses: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"
      headerContainerClasses: "text-center mb-16"
      titleClasses: "text-4xl font-bold text-gray-900 mb-4"
      subtitleClasses: "text-xl text-gray-600"
      # Grid styles
      gridContainerClasses: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8"
      featureCardClasses: "bg-white rounded-lg shadow-sm p-8 hover:shadow-lg transition-shadow duration-300"
      # Feature icon styles
      iconWrapperClasses: "flex items-center justify-center w-12 h-12 rounded-md bg-gradient-to-r from-purple-600 to-indigo-600 text-white mb-6"
      iconClasses: "w-6 h-6"
      # Feature content styles
      featureTitleClasses: "text-xl font-semibold text-gray-900 mb-3"
      featureDescriptionClasses: "text-gray-600"
      features: [
        {
          "icon": "heroicon-o-template",
          "title": "Component Library",
          "description": "Pre-built components ready for your next project"
        },
        {
          "icon": "heroicon-o-code",
          "title": "Custom Development",
          "description": "Build your own components with simple commands"
        }
      ]

layouts:
  bonsai:
    sections:
      - site_header
      - home_hero
      - services_card
      - features_widget
      - pricing
      - feature_grid

pages:
  home:
    title: "Bonsai CLI"
    layout: bonsai
    is_homepage: true

# WordPress specific configurations
wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    
  image_sizes:
    hero_image:
      width: 1920
      height: 1080
      crop: true

# Asset compilation settings
assets:
  styles:
    - resources/styles/bonsai.scss
  scripts:
    - resources/scripts/bonsai.js