name: Bonsai CLI
description: WordPress CLI tool for generating and managing reusable components
version: 0.0.1

# Add theme settings at the top level
theme:
  body:
    class: 'bg-gray-100'

# ASCII art configuration section
ascii_art:
  default: |
    ${green}                    &
                          && & &
                        & &&&&&~&
                         &  &&&&
                          &&&~|\
                           &//~
                          |/
                         /|\
               &&       |//~
                 &&    \_/     && & &
          &&&    &&     //_/  /&&&/_&&&
           &&&__&&   \_\_\/~/   &&&
         & &\&  &&&&\|&  /~|     &
          &&& & &    /~~
                   ${brown}:___________./~~~\.___:
                    \                     /
                     \_________________/
                     (_)           (_)${reset}

components:
  - hero
  - header
  - card
  - widget
  - pricing-box

sections:
  site_header:
    component: header
    data:
      siteName: "Bonsai"
      iconComponent: "heroicon-o-command-line"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#commands", "label": "Commands"},
        {"url": "#docs", "label": "Documentation"}
      ]
      primaryLink: "https://github.com/jackalopelabs/bonsai-cli"
      containerClasses: "max-w-5xl mx-auto"
      containerInnerClasses: "px-6"
      headerClass: "bg-indigo-500 bg-opacity-60 backdrop-blur-md shadow-lg border border-transparent rounded-full mx-auto p-1 my-4"
  
  home_hero:
    component: hero
    data:
      title: "Bonsai-CLI"
      subtitle: "WordPress Component Management"
      description: "A WordPress CLI tool for generating and managing reusable components in Roots-based projects"
      imagePaths: ["https://placehold.co/600x400/png"]
      buttonText: "Get Started"
      buttonLink: "#installation"
      secondaryText: "View Docs"
      secondaryLink: "#documentation"
      buttonLinkIcon: true
      secondaryIcon: true
      iconMappings:
        dropdownIcon: "heroicon-s-chevron-down"
        buttonLinkIcon: "heroicon-s-arrow-down-tray"
        secondaryIcon: "heroicon-s-arrow-right"
  
  services_card:
    component: card
    data:
      sectionId: "services"
      sectionTitle: "<span class=\"hidden sm:inline\">Our</span> Services"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#docs", "label": "Documentation"}
      ]
      featureItems: [
        {
          "icon": "heroicon-o-command-line",
          "title": "Component Generation",
          "description": "Generate reusable components with a single command."
        },
        {
          "icon": "heroicon-o-puzzle-piece",
          "title": "Section Builder",
          "description": "Create and manage page sections with dynamic data."
        },
        {
          "icon": "heroicon-o-template",
          "title": "Template System",
          "description": "Pre-built templates for rapid WordPress development."
        }
      ]

  features_widget:
    component: widget
    data:
      items:
        - id: "widget-1"
          title: "Component Generation"
          icon: "heroicon-o-command-line"
          content: ""
          cta:
            title: "Component Generation"
            link: "#components"
            imagePath: "https://placehold.co/600x400/png"
          description: "Generate and manage reusable components with ease:"
          listItems:
            - number: 1
              itemName: "Quick Setup"
              text: "Initialize your project with bonsai:init"
            - number: 2
              itemName: "Component Library"
              text: "Access pre-built components ready for customization"
            - number: 3
              itemName: "Custom Components"
              text: "Create your own components with simple commands"

        - id: "widget-2"
          title: "Section Builder"
          icon: "heroicon-o-puzzle-piece"
          content: ""
          cta:
            title: "Section Builder"
            link: "#sections"
            imagePath: "https://placehold.co/600x400/png"
          description: "Build dynamic page sections with powerful features:"
          listItems:
            - number: 1
              itemName: "Dynamic Data"
              text: "Configure sections using YAML files"
            - number: 2
              itemName: "Reusable Sections"
              text: "Create once, use anywhere in your site"
            - number: 3
              itemName: "Flexible Layout"
              text: "Combine sections into custom page layouts"

        - id: "widget-3"
          title: "Template System"
          icon: "heroicon-o-template"
          content: ""
          cta:
            title: "Template System"
            link: "#templates"
            imagePath: "https://placehold.co/600x400/png"
          description: "Generate complete WordPress sites from templates:"
          listItems:
            - number: 1
              itemName: "Pre-built Templates"
              text: "Start with our collection of ready-to-use templates"
            - number: 2
              itemName: "Custom Templates"
              text: "Create your own templates for reuse"
            - number: 3
              itemName: "WordPress Integration"
              text: "Seamlessly works with WordPress and Sage"

  pricing:
    component: pricing-box
    data:
      title: "Choose Your Plan"
      subtitle: "Limited-time pricing available now"
      description: "Select the plan that best suits your needs. Lock in your price early and keep it forever, or until you cancel."
      pricingBoxes: [
        {
          "icon": "heroicon-o-command-line",
          "iconColor": "text-gray-400",
          "planType": "Basic",
          "price": "Free",
          "features": [
            "Generate components",
            "Basic templates",
            "Documentation access"
          ],
          "ctaLink": "#get-started",
          "ctaText": "Get Started",
          "ctaColor": "bg-white",
          "iconBtn": "heroicon-o-arrow-right",
          "iconBtnColor": "text-gray-500"
        },
        {
          "icon": "heroicon-o-puzzle-piece",
          "iconColor": "text-gray-500",
          "planType": "Pro",
          "price": "$99<span class=\"text-xs text-gray-400\">/yr</span>",
          "features": [
            "All Basic features",
            "Custom components",
            "Advanced templates",
            "Priority support",
            "Early access"
          ],
          "ctaLink": "#buy-pro",
          "ctaText": "Buy Now",
          "ctaColor": "bg-gradient-to-r from-emerald-600 to-green-500 text-white",
          "iconBtn": "heroicon-o-shopping-cart",
          "iconBtnColor": "text-white"
        },
        {
          "icon": "heroicon-o-star",
          "iconColor": "text-yellow-500",
          "planType": "Sensei",
          "price": "$249<span class=\"text-xs text-gray-400\">/yr</span>",
          "features": [
            "All Pro features",
            "Custom development",
            "Private Slack channel",
            "1-on-1 mentoring",
            "Early beta access",
            "Custom integrations",
            "Architecture review"
          ],
          "ctaLink": "#buy-sensei",
          "ctaText": "Buy Now",
          "ctaColor": "bg-gradient-to-r from-yellow-500 to-amber-500 text-white",
          "iconBtn": "heroicon-o-shopping-cart",
          "iconBtnColor": "text-white"
        }
      ]

layouts:
  bonsai:
    sections:
      - site_header
      - home_hero
      - services_card
      - features_widget
      - pricing

pages:
  home:
    title: "Bonsai CLI"
    layout: bonsai
    is_homepage: true

# WordPress specific configurations
wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    
  image_sizes:
    hero_image:
      width: 1920
      height: 1080
      crop: true

# Asset compilation settings
assets:
  styles:
    - resources/styles/bonsai.scss
  scripts:
    - resources/scripts/bonsai.js