name: Cypress Template
description: A modern, minimal business website template
version: 1.0.0

# Component Definitions
components:
  - hero
  - faq
  - cta
  - card-featured
  - slideshow
  - widget
  - table

# Layout Definitions
layouts:
  main:
    template: "bonsai"
    sections:
      - home_hero
      - features
      - services_faq
  
  landing:
    template: "bonsai"
    sections:
      - home_hero
      - features

# Page Configurations
pages:
  cypress:
    title: "Cypress"
    layout: main
    template: "template-bonsai-cypress"
    is_homepage: true
    meta:
      description: "Welcome to Cypress - Modern Web Testing"
      keywords: "testing, automation, cypress, end-to-end testing"
  
  docs:
    title: "Documentation"
    layout: main
    template: "template-bonsai-docs"
    meta:
      description: "Cypress Documentation - Learn how to test your applications"

# Database Configuration
database:
  seeds:
    - CypressDefaultContentSeeder
    - CypressMenuSeeder
  imports:
    - initial-content.sql

# Site Settings
settings:
  options:
    blogname: "Cypress"
    blogdescription: "Modern Web Testing"
    timezone_string: "America/New_York"
  env:
    WP_ENV: "production"
    MAIL_DRIVER: "smtp"
  api_keys:
    mailchimp:
      api_key: "${MAILCHIMP_API_KEY}"
      list_id: "${MAILCHIMP_LIST_ID}"
    google:
      analytics_id: "${GA_TRACKING_ID}"