name: Cypress Template
description: Modern SaaS landing page template
version: 1.0.0

components:
  - hero

sections:
  home_hero:
    component: hero
    data:
      title: "Welcome to Cypress"
      subtitle: "Modern Solutions for Modern Businesses"
      description: "A modern web testing tool for modern applications"
      imagePaths: ["images/hero-main.jpg"]
      buttonText: "Get Started"
      buttonLink: "#contact"
      secondaryText: "Watch Demo"
      secondaryLink: "#demo"
      buttonLinkIcon: true
      secondaryIcon: true

layouts:
  cypress:
    sections:
      - home_hero

pages:
  home:
    title: "Cypress"
    layout: cypress
    is_homepage: true