name: Bonsai Cypress
description: Premium WordPress theme with no-code editing capabilities
version: 0.0.1

ascii_art:
  default: |
    ${green}                    &
                          && & &
                      & &&&&&&~&&&
                       &&  &&&&  &&
                        &&&~|\&&&
                         &//~\\&
                        |/    \|
                       /|\    /|\
             &&       |//~    ~\\|
               &&    \_/        \_/  && & &
        &&&    &&     //_/____\\_\  /&&&/_&&&
         &&&__&&   \_\_\/~~~~\/\_/   &&&
       & &\&  &&&&\|&  /~||~\  &|     &
        &&& & &    /~~      ~~\
                 ${brown}:____________./~~~\.____:
                  \                         /
                   \_____________________/
                   (_)               (_)${reset}

components:
  - hero
  - header
  - card
  - widget
  - pricing-box

sections:
  site_header:
    component: header
    data:
      siteName: "Cypress"
      iconComponent: "heroicon-o-sparkles"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#pricing", "label": "Pricing"},
        {"url": "#templates", "label": "Templates"},
        {"url": "#docs", "label": "Documentation"}
      ]
      primaryLink: "https://cypress.bonsai-cli.com"
      containerClasses: "max-w-7xl mx-auto"
      containerInnerClasses: "px-4 sm:px-6 lg:px-8"
  
  home_hero:
    component: hero
    data:
      title: "The Future of WordPress Development"
      subtitle: "No-Code Meets Developer Freedom"
      description: "Experience the perfect blend of visual editing and developer control with Cypress - the premium WordPress theme powered by Bonsai CLI"
      imagePaths: ["https://cypress.bonsai-cli.com/hero-preview.png"]
      buttonText: "Start Building"
      buttonLink: "#pricing"
      secondaryText: "Watch Demo"
      secondaryLink: "#demo"
      buttonLinkIcon: true
      secondaryIcon: true
      iconMappings:
        dropdownIcon: "heroicon-s-chevron-down"
        buttonLinkIcon: "heroicon-s-sparkles"
        secondaryIcon: "heroicon-s-play"
  
  services_card:
    component: card
    data:
      title: "Premium Features"
      subtitle: "Everything you need to build professional WordPress sites"
      features: [
        {
          "icon": "heroicon-o-paint-brush",
          "title": "Visual Builder",
          "description": "Intuitive drag-and-drop interface for content editing"
        },
        {
          "icon": "heroicon-o-code-bracket",
          "title": "Developer Tools",
          "description": "Full development control with Bonsai CLI integration"
        },
        {
          "icon": "heroicon-o-cube-transparent",
          "title": "Block Library",
          "description": "Extensive collection of custom Gutenberg blocks"
        },
        {
          "icon": "heroicon-o-squares-2x2",
          "title": "Template System",
          "description": "Pre-built layouts for rapid site development"
        }
      ]

  features_widget:
    component: widget
    data:
      title: "Loved by Developers"
      subtitle: "See what others are saying about Cypress"
      testimonials: [
        {
          "avatar": "https://cypress.bonsai-cli.com/avatars/1.jpg",
          "name": "Sarah Johnson",
          "role": "Lead Developer",
          "company": "TechCorp",
          "quote": "Cypress has revolutionized how we build WordPress sites. The no-code interface is perfect for clients, while maintaining the developer experience we love."
        },
        {
          "avatar": "https://cypress.bonsai-cli.com/avatars/2.jpg",
          "name": "Michael Chen",
          "role": "Agency Owner",
          "company": "PixelPerfect",
          "quote": "The combination of Bonsai CLI and visual editing has cut our development time in half. It's a game-changer."
        }
      ]

  pricing:
    component: pricing-box
    data:
      title: "Choose Your License"
      subtitle: "Flexible options for every need"
      description: "All plans include premium support and regular updates. Plus, lock in your price forever."
      pricingBoxes: [
        {
          "icon": "heroicon-o-building-storefront",
          "iconColor": "text-purple-500",
          "planType": "Single Site",
          "price": "$199",
          "features": [
            "1 site license",
            "All premium features",
            "Visual builder",
            "Premium support",
            "Regular updates"
          ],
          "ctaLink": "#buy-single",
          "ctaText": "Purchase",
          "ctaColor": "bg-white",
          "iconBtn": "heroicon-o-arrow-right",
          "iconBtnColor": "text-gray-500"
        },
        {
          "icon": "heroicon-o-building-office-2",
          "iconColor": "text-indigo-600",
          "planType": "Agency",
          "price": "$499",
          "features": [
            "5 site licenses",
            "White labeling",
            "Priority support",
            "Client management",
            "Advanced blocks",
            "Early access"
          ],
          "ctaLink": "#buy-agency",
          "ctaText": "Purchase",
          "ctaColor": "bg-gradient-to-r from-emerald-600 to-green-500 text-white",
          "iconBtn": "heroicon-o-shopping-cart",
          "iconBtnColor": "text-white"
        },
        {
          "icon": "heroicon-o-globe-americas",
          "iconColor": "text-blue-600",
          "planType": "Unlimited",
          "price": "$999",
          "features": [
            "Unlimited sites",
            "All Agency features",
            "Custom development",
            "VIP support",
            "1-on-1 training",
            "Custom integrations",
            "Beta access"
          ],
          "ctaLink": "#buy-unlimited",
          "ctaText": "Purchase",
          "ctaColor": "bg-gradient-to-r from-yellow-500 to-amber-500 text-white",
          "iconBtn": "heroicon-o-shopping-cart",
          "iconBtnColor": "text-white"
        }
      ]

layouts:
  cypress:
    sections:
      - home_hero
      - features_widget
      - services_card
      - pricing
      - site_header

pages:
  home:
    title: "Cypress - Premium WordPress Theme"
    layout: cypress
    is_homepage: true
    meta:
      _wp_page_template: templates/template-cypress.blade.php

wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
    footer_navigation:
      location: "footer_navigation"
      name: "Footer Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    - gutenberg
    - wide-images
    - responsive-embeds
    
  image_sizes:
    hero_image:
      width: 2560
      height: 1440
      crop: true
    feature_image:
      width: 800
      height: 600
      crop: true
    testimonial_avatar:
      width: 96
      height: 96
      crop: true

assets:
  styles:
    - resources/styles/cypress.scss
    - resources/styles/editor.scss
  scripts:
    - resources/scripts/cypress.js
    - resources/scripts/gutenberg.js