name: Cypress Template
description: Modern SaaS landing page template
version: 1.0.0

components:
  - hero
  - header

sections:
  header:
    component: header
    data:
      siteName: "Cypress"
      iconComponent: "heroicon-o-cube-transparent"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#pricing", "label": "Pricing"},
        {"url": "#faq", "label": "FAQ"}
      ]
      primaryLink: "#signup"
      containerClasses: "max-w-5xl mx-auto"
      containerInnerClasses: "px-6"
  
  home_hero:
    component: hero
    data:
      title: "Welcome to Cypress"
      subtitle: "Modern Solutions for Modern Businesses"
      description: "A modern web testing tool for modern applications"
      imagePaths: ["https://placehold.co/600x400/png"]
      buttonText: "Get Started"
      buttonLink: "#contact"
      secondaryText: "Watch Demo"
      secondaryLink: "#demo"
      buttonLinkIcon: true
      secondaryIcon: true

layouts:
  cypress:
    sections:
      - header
      - home_hero

pages:
  home:
    title: "Cypress"
    layout: cypress
    is_homepage: true