name: Cypress
description: Agency-focused WordPress theme optimized for landing pages with no-code editing capabilities
version: 0.0.1

# Add theme settings at the top level
theme:
  body:
    class: 'bg-white'

# ASCII art configuration section
ascii_art:
  default: |
    ${green}                    &
                          && & &
                      & &&&&&&~&&&
                       &&  &&&&  &&
                        &&&~|\&&&
                         &//~\\&
                        |/    \|
                       /|\    /|\
             &&       |//~    ~\\|
               &&    \_/        \_/  && & &
        &&&    &&     //_/____\\_\  /&&&/_&&&
         &&&__&&   \_\_\/~~~~\/\_/   &&&
       & &\&  &&&&\|&  /~||~\  &|     &
        &&& & &    /~~      ~~\
                 ${brown}:____________./~~~\.____:
                  \                         /
                   \_____________________/
                   (_)               (_)${reset}

components:
  - hero
  - header
  - card
  - widget
  - pricing-box

sections:
  site_header:
    component: header
    data:
      siteName: "Cypress"
      iconComponent: "heroicon-o-sparkles"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#pricing", "label": "Pricing"},
        {"url": "#templates", "label": "Templates"},
        {"url": "#docs", "label": "Documentation"}
      ]
      primaryLink: "https://cypress.bonsai-cli.com"
      # Style Classes
      containerClasses: "max-w-5xl mx-auto"
      containerInnerClasses: "px-6"
      headerClass: "bg-indigo-500 bg-opacity-60 backdrop-blur-md shadow-lg border border-transparent rounded-full mx-auto p-1 my-4"
      iconClasses: "h-8 w-8 mr-2 p-1"
      chevronClasses: "w-4 h-4 ml-2 inline-block"
      buttonText: "Plans"
      buttonPrefix: "See"

  home_hero:
    component: hero
    data:
      # Content
      title: "Elevate Your Agency's Web Presence"
      subtitle: "Sleek Design Meets Powerful Functionality"
      description: "Cypress offers a streamlined approach to creating stunning landing pages with the flexibility of no-code editing and developer-friendly tools."
      imagePaths: ["https://placehold.co/600x400/png"]
      buttonText: "Get Started"
      buttonLink: "#pricing"
      secondaryText: "View Demo"
      secondaryLink: "#demo"
      buttonLinkIcon: true
      secondaryIcon: true
      
      # Style Classes
      containerClasses: "container mx-auto px-4 mb-12 mt-0 md:mt-24"
      columnClasses: "flex flex-col md:flex-row items-center md:items-start -mx-4"
      imageColumnClasses: "w-full md:w-1/2 px-4 flex justify-center items-center mt-12 md:mt-0 md:order-last"
      textColumnClasses: "w-full md:w-1/2 px-4"
      titleClass: "font-semibold text-6xl"
      productTagClasses: "bg-white bg-opacity-50 px-3 py-1 text-sm inline-block"
      productIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      buttonClasses: "bg-gradient-to-r from-indigo-500 to-blue-600 text-white text-xl py-2 px-5 rounded-full"
      buttonIconClasses: "text-white w-6 h-6 ml-2 inline-block align-middle"
      secondaryClasses: "text-sm bg-transparent px-2 py-1 backdrop-blur-md shadow-lg rounded-md border border-gray-100"
      secondaryIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      
      # Icons
      iconMappings:
        dropdownIcon: "heroicon-s-chevron-down"
        buttonLinkIcon: "heroicon-s-sparkles"
        secondaryIcon: "heroicon-s-play"

  services_card:
    component: card
    data:
      sectionId: "services"
      sectionTitle: "<span class=\"hidden sm:inline\">Our</span> Services"
      navLinks: [
        {"url": "#features", "label": "Features"},
        {"url": "#docs", "label": "Documentation"}
      ]
      # Style classes
      sectionClasses: "py-12"
      containerClasses: "max-w-4xl mx-auto px-6"
      navContainerClasses: "flex flex-col sm:flex-row flex-wrap items-start mb-6 justify-center md:justify-center"
      titleClasses: "text-lg text-gray-700 bg-white p-3 rounded-lg mr-4 mb-4 sm:mb-0"
      titleIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      navLinkClasses: "text-lg text-gray-700 p-3 mb-4 sm:mb-0 hidden sm:inline"
      navLinkIconClasses: "w-4 h-4 ml-2 inline-block align-middle"
      # Card styles
      cardContainerClasses: "bg-white bg-opacity-50 grid md:grid-cols-2 gap-8 rounded-3xl p-3"
      imageColumnClasses: "md:w-1/2 mx-auto"
      featuresColumnClasses: "md:w-2/2 space-y-6"
      featureItemClasses: "flex items-start space-x-4 bg-white rounded-xl p-3"
      featureIconClasses: "h-6 w-6 text-indigo-500"
      featureTitleClasses: "text-lg font-semibold"
      featureDescriptionClasses: "text-sm text-gray-500"
      featureItems: [
        {
          "icon": "heroicon-o-command-line",
          "title": "Component Generation",
          "description": "Generate reusable components with a single command."
        },
        {
          "icon": "heroicon-o-puzzle-piece",
          "title": "Section Builder",
          "description": "Create and manage page sections with dynamic data."
        },
        {
          "icon": "heroicon-o-template",
          "title": "Template System",
          "description": "Pre-built templates for rapid WordPress development."
        }
      ]

  features_widget:
    component: widget
    data:
      # Global widget styles
      globalStyles:
        containerClasses: "bg-white bg-opacity-30 shadow-lg rounded-xl"
        contentClasses: "p-2"
        descriptionClasses: "text-gray-600 text-sm"
        noteClasses: "text-gray-600 text-sm"
        noteLabelClasses: "font-bold"

      # Global list item styles
      listItemStyles:
        listItemClasses: "flex items-start py-2"
        numberClasses: "flex-shrink-0 flex items-center justify-center text-white mr-4 bg-gray-600 rounded-full w-8 h-8 text-sm"
        contentClasses: ""
        titleClasses: "font-semibold"
        textClasses: "text-sm text-gray-500"

      # Global CTA styles
      ctaStyles:
        containerClasses: "cta bg-white bg-opacity-50 rounded-lg flex items-center space-x-8 mt-2"
        imageClasses: "w-44 h-44 object-cover rounded-xl"
        contentContainerClasses: "flex items-center justify-between flex-1"
        titleClasses: "text-xl font-semibold"
        buttonClasses: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
        buttonIconClasses: "w-4 h-4 ml-2"

      items:
        - id: "widget-1"
          title: "Component Generation"
          icon: "heroicon-o-command-line"
          content: ""
          cta:
            title: "Component Generation"
            link: "#components"
            imagePath: "https://placehold.co/600x400/png"
          description: "Generate and manage reusable components with ease:"
          listItems:
            - number: 1
              itemName: "Quick Setup"
              text: "Initialize your project with bonsai:init"
            - number: 2
              itemName: "Component Library"
              text: "Access pre-built components ready for customization"
            - number: 3
              itemName: "Custom Components"
              text: "Create your own components with simple commands"

        - id: "widget-2"
          title: "Section Builder"
          icon: "heroicon-o-puzzle-piece"
          content: ""
          cta:
            title: "Section Builder"
            link: "#sections"
            imagePath: "https://placehold.co/600x400/png"
          description: "Build dynamic page sections with powerful features:"
          listItems:
            - number: 1
              itemName: "Dynamic Data"
              text: "Configure sections using YAML files"
            - number: 2
              itemName: "Reusable Sections"
              text: "Create once, use anywhere in your site"
            - number: 3
              itemName: "Flexible Layout"
              text: "Combine sections into custom page layouts"

        - id: "widget-3"
          title: "Template System"
          icon: "heroicon-o-template"
          content: ""
          cta:
            title: "Template System"
            link: "#templates"
            imagePath: "https://placehold.co/600x400/png"
          description: "Generate complete WordPress sites from templates:"
          listItems:
            - number: 1
              itemName: "Pre-built Templates"
              text: "Start with our collection of ready-to-use templates"
            - number: 2
              itemName: "Custom Templates"
              text: "Create your own templates for reuse"
            - number: 3
              itemName: "WordPress Integration"
              text: "Seamlessly works with WordPress and Sage"

  pricing:
    component: pricing-box
    data:
      # Global pricing box styles
      pricingBoxStyles:
        containerClasses: "bg-white bg-opacity-50 rounded-xl shadow-lg overflow-hidden mx-auto md:mx-0 text-center my-3 transition-transform transform hover:scale-105"
        iconClasses: "inline-block h-12 w-12 mt-8 mb-4"
        planTypeClasses: "text-gray-400"
        priceClasses: "text-4xl font-bold"
        dividerClasses: "border-t border-gray-200 my-5"
        featureListClasses: "my-4 text-left space-y-3"
        featureItemClasses: "flex items-center justify-start text-gray-500"
        featureIconClasses: "w-5 h-5 mr-2"
        ctaButtonClasses: "inline-block py-2 px-6 rounded-full"
        ctaIconClasses: "inline-block h-4 w-4 ml-2"

      title: "Flexible Pricing Plans"
      subtitle: "Choose a plan that fits your agency's needs"
      description: "All plans include premium support and regular updates. Upgrade anytime to unlock more features."
      pricingBoxes:
        - icon: "heroicon-o-building-storefront"
          iconColor: "text-purple-500"
          planType: "Starter"
          price: "$99"
          features:
            - "3 site licenses"
            - "All premium features"
            - "Visual builder access"
            - "Standard support"
            - "Regular updates"
          ctaLink: "#buy-starter"
          ctaText: "Purchase"
          ctaColor: "bg-white"
          iconBtn: "heroicon-o-arrow-right"
          iconBtnColor: "text-gray-500"

        - icon: "heroicon-o-building-office-2"
          iconColor: "text-indigo-600"
          planType: "Professional"
          price: "$299"
          features:
            - "10 site licenses"
            - "White labeling"
            - "Priority support"
            - "Client management tools"
            - "Advanced templates"
            - "Early access to new features"
          ctaLink: "#buy-professional"
          ctaText: "Purchase"
          ctaColor: "bg-gradient-to-r from-emerald-600 to-green-500 text-white"
          iconBtn: "heroicon-o-shopping-cart"
          iconBtnColor: "text-white"

        - icon: "heroicon-o-globe-americas"
          iconColor: "text-blue-600"
          planType: "Enterprise"
          price: "$799"
          features:
            - "Unlimited site licenses"
            - "All Professional features"
            - "Custom development services"
            - "VIP support"
            - "Dedicated account manager"
            - "1-on-1 training sessions"
            - "Custom integrations"
          ctaLink: "#buy-enterprise"
          ctaText: "Purchase"
          ctaColor: "bg-gradient-to-r from-yellow-500 to-amber-500 text-white"
          iconBtn: "heroicon-o-shopping-cart"
          iconBtnColor: "text-white"

layouts:
  cypress:
    sections:
      - site_header
      - home_hero
      - services_card
      - features_widget
      - pricing

pages:
  home:
    title: "Cypress - Agency WordPress Theme"
    layout: cypress
    is_homepage: true
    meta:
      _wp_page_template: templates/template-cypress.blade.php

# WordPress specific configurations
wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
    footer_navigation:
      location: "footer_navigation"
      name: "Footer Navigation"

  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    - gutenberg
    - wide-images
    - responsive-embeds

  image_sizes:
    hero_image:
      width: 2560
      height: 1440
      crop: true
    feature_image:
      width: 800
      height: 600
      crop: true
    testimonial_avatar:
      width: 96
      height: 96
      crop: true

# Asset compilation settings
assets:
  styles:
    - resources/styles/cypress.scss
    - resources/styles/editor.scss
  scripts:
    - resources/scripts/cypress.js
    - resources/scripts/gutenberg.js
