name: Cypress Template
description: Modern SaaS landing page template
version: 1.0.0

components:
  - hero

sections:
  home_hero:
    component: hero
    data:
      title: "Welcome to Cypress"
      subtitle: "Modern Solutions for Modern Businesses"
      description: "A modern web testing tool for modern applications"
      imagePath: "images/hero-main.jpg"
      l1: "Streamlined Workflow"
      l2: "Enhanced Productivity"
      l3: "Data-Driven Insights"
      l4: "24/7 Support"
      primaryText: "Get Started"
      primaryLink: "#contact"
      secondaryText: "Watch Demo"

layouts:
  cypress:
    sections:
      - home_hero

pages:
  home:
    title: "Cypress"
    layout: cypress
    is_homepage: true