name: Best Health Coverage
description: Comprehensive health insurance and benefits solutions
version: 0.0.1

ascii_art:
  default: |
    ${green}                    &
                          && & &
                        & &&&&&~&
                         &  &&&&
                          &&&~|\
                           &//~
                          |/
                         /|\
               &&       |//~
                 &&    \_/     && & &
          &&&    &&     //_/  /&&&/_&&&
           &&&__&&   \_\_\/~/   &&&
         & &\&  &&&&\|&  /~|     &
          &&& & &    /~~
                   ${brown}:___________./~~~\.___:
                    \                     /
                     \_________________/
                     (_)           (_)${reset}

components:
  - hero
  - header
  - card
  - widget
  - pricing-box

sections:
  site_header:
    component: header
    data:
      siteName: "Best Health Coverage"
      iconComponent: "heroicon-o-heart"
      navLinks: [
        {"url": "#plans", "label": "Plans"},
        {"url": "#benefits", "label": "Benefits"},
        {"url": "#providers", "label": "Find Providers"},
        {"url": "#contact", "label": "Contact Us"}
      ]
      primaryLink: "https://besthealthcoverage.com/enroll"
      containerClasses: "max-w-7xl mx-auto"
      containerInnerClasses: "px-4 sm:px-6 lg:px-8"
  
  home_hero:
    component: hero
    data:
      title: "Your Health, Your Choice"
      subtitle: "Affordable Care Act Compliant Coverage"
      description: "Comprehensive health insurance plans that protect you and your family. Including medical, dental, vision, and critical illness coverage."
      imagePaths: ["https://placehold.co/600x400/png"]
      buttonText: "Get Coverage"
      buttonLink: "#plans"
      secondaryText: "Find a Provider"
      secondaryLink: "#providers"
      buttonLinkIcon: true
      secondaryIcon: true
      iconMappings:
        dropdownIcon: "heroicon-s-chevron-down"
        buttonLinkIcon: "heroicon-s-shield-check"
        secondaryIcon: "heroicon-s-map-pin"
  
  services_card:
    component: card
    data:
      sectionId: "coverage"
      sectionTitle: "Complete Coverage"
      navLinks: [
        {"url": "#benefits", "label": "Benefits"},
        {"url": "#enroll", "label": "Enroll Now"}
      ]
      featureItems: [
        {
          "icon": "heroicon-o-heart",
          "title": "Medical Coverage",
          "description": "Comprehensive medical coverage including preventive care, specialists, and hospital stays."
        },
        {
          "icon": "heroicon-o-tooth",
          "title": "Dental Care",
          "description": "Preventive, basic, and major dental services with access to nationwide providers."
        },
        {
          "icon": "heroicon-o-eye",
          "title": "Vision Benefits",
          "description": "Eye exams, glasses, contacts, and discounts on vision correction procedures."
        }
      ]

  features_widget:
    component: widget
    data:
      items:
        - id: "widget-1"
          title: "Medical Coverage"
          icon: "heroicon-o-heart"
          content: ""
          cta:
            title: "Medical Plans"
            link: "#medical-plans"
            imagePath: "https://placehold.co/600x400/png"
          description: "Comprehensive medical coverage including:"
          listItems:
            - number: 1
              itemName: "Preventive Care"
              text: "100% covered annual check-ups and screenings"
            - number: 2
              itemName: "Prescription Drugs"
              text: "Affordable prescriptions with nationwide pharmacy network"
            - number: 3
              itemName: "Hospital Care"
              text: "Inpatient and outpatient services coverage"

        - id: "widget-2"
          title: "Dental Benefits"
          icon: "heroicon-o-tooth"
          content: ""
          cta:
            title: "Dental Plans"
            link: "#dental-plans"
            imagePath: "https://placehold.co/600x400/png"
          description: "Complete dental care coverage:"
          listItems:
            - number: 1
              itemName: "Preventive Services"
              text: "Free cleanings and check-ups twice per year"
            - number: 2
              itemName: "Basic Services"
              text: "Fillings, extractions, and basic procedures"
            - number: 3
              itemName: "Major Services"
              text: "Root canals, crowns, and orthodontics"

        - id: "widget-3"
          title: "Vision Care"
          icon: "heroicon-o-eye"
          content: ""
          cta:
            title: "Vision Plans"
            link: "#vision-plans"
            imagePath: "https://placehold.co/600x400/png"
          description: "Comprehensive vision benefits:"
          listItems:
            - number: 1
              itemName: "Annual Exams"
              text: "Covered eye exams with low copay"
            - number: 2
              itemName: "Eyewear Coverage"
              text: "Allowance for glasses or contacts"
            - number: 3
              itemName: "LASIK Benefits"
              text: "Discounts on laser vision correction"

  pricing:
    component: pricing
    data:
      title: "Health Insurance Plans"
      subtitle: "ACA-Compliant Coverage Options"
      description: "Choose the plan that best fits your needs and budget. All plans include essential health benefits required by the Affordable Care Act."
      pricingBoxes:
        - icon: "heroicon-o-shield-check"
          iconColor: "text-blue-500"
          planType: "Bronze"
          price: "$299"
          features:
            - "Lower monthly premium"
            - "Higher deductible"
            - "ACA compliant"
            - "Preventive care covered"
            - "Prescription coverage"
          ctaLink: "#enroll-bronze"
          ctaText: "Choose Plan"
          ctaColor: "bg-white"
          iconBtn: "heroicon-o-arrow-right"
          iconBtnColor: "text-gray-500"
        
        - icon: "heroicon-o-shield-check"
          iconColor: "text-silver-500"
          planType: "Silver"
          price: "$399"
          features:
            - "Moderate monthly premium"
            - "Moderate deductible"
            - "Lower copays"
            - "Dental coverage included"
            - "Vision coverage included"
            - "Specialist visits"
          ctaLink: "#enroll-silver"
          ctaText: "Choose Plan"
          ctaColor: "bg-gradient-to-r from-blue-600 to-cyan-600 text-white"
          iconBtn: "heroicon-o-arrow-right"
          iconBtnColor: "text-white"
        
        - icon: "heroicon-o-shield-check"
          iconColor: "text-gold-500"
          planType: "Gold"
          price: "$499"
          features:
            - "Higher monthly premium"
            - "Lowest deductible"
            - "Lowest copays"
            - "Enhanced dental & vision"
            - "Critical illness coverage"
            - "Worldwide coverage"
            - "Alternative medicine"
          ctaLink: "#enroll-gold"
          ctaText: "Choose Plan"
          ctaColor: "bg-gradient-to-r from-yellow-500 to-amber-500 text-white"
          iconBtn: "heroicon-o-arrow-right"
          iconBtnColor: "text-white"

layouts:
  health:
    sections:
      - site_header
      - home_hero
      - services_card
      - features_widget
      - pricing

pages:
  home:
    title: "Best Health Coverage - Comprehensive Health Insurance Plans"
    layout: health
    is_homepage: true

wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
    footer_navigation:
      location: "footer_navigation"
      name: "Footer Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    
  image_sizes:
    hero_image:
      width: 1920
      height: 1080
      crop: true
    benefit_image:
      width: 800
      height: 600
      crop: true

assets:
  styles:
    - resources/styles/health.scss
  scripts:
    - resources/scripts/health.js