ascii_art:
  default: "${green}                    &\n                      && & &\n        \
    \            & &&&&&~&\n                     &  &&&&\n                      &&&~|\\\
    \n                       &//~\n                      |/\n                    \
    \ /|\\\n           &&       |//~\n             &&    \\_/     && & &\n      &&&\
    \    &&     //_/  /&&&/_&&&\n       &&&__&&   \\_\\_\\/~/   &&&\n     & &\\& \
    \ &&&&\\|&  /~|     &\n      &&& & &    /~~\n               ${brown}:___________./~~~\\\
    .___:\n                \\                     /\n                 \\_________________/\n\
    \                 (_)           (_)${reset}\n"
assets:
  scripts:
  - resources/scripts/hydrofera.js
  styles:
  - resources/styles/hydrofera.scss
components:
- hero
- header
- card
- widget
- pricing-box
description: Showcasing Hydrofera's innovative wound care solutions.
layouts:
  hydrofera:
    sections:
    - site_header
    - home_hero
    - solutions_card
    - pricing
name: Hydrofera Blue
pages:
  home:
    is_homepage: true
    layout: hydrofera
    title: Hydrofera Blue
sections:
  home_hero:
    component: hero
    data:
      buttonLink: '#products'
      buttonLinkIcon: true
      buttonText: Learn More
      description: Hydrofera Blue offers advanced wound care products that promote
        healing and protect against infection.
      iconMappings:
        buttonLinkIcon: heroicon-s-information-circle
        dropdownIcon: heroicon-s-chevron-down
        secondaryIcon: heroicon-s-envelope
      imagePaths:
      - https://placehold.co/600x400/png
      secondaryIcon: true
      secondaryLink: '#contact'
      secondaryText: Contact Us
      subtitle: Innovative Wound Care Solutions
      title: Hydrofera Blue
  pricing:
    component: pricing
    data:
      pricingBoxes:
      - ctaColor: bg-blue-500 text-white
        ctaLink: '#buy-standard'
        ctaText: Buy Now
        features:
        - General wound care
        - Antibacterial protection
        icon: heroicon-o-medical-bag
        iconBtn: heroicon-o-shopping-cart
        iconBtnColor: text-white
        iconColor: text-blue-500
        planType: Standard
        price: $50
      - ctaColor: bg-pink-500 text-white
        ctaLink: '#buy-advanced'
        ctaText: Buy Now
        features:
        - Enhanced healing
        - Advanced infection control
        - For chronic wounds
        icon: heroicon-o-heart
        iconBtn: heroicon-o-shopping-cart
        iconBtnColor: text-white
        iconColor: text-pink-500
        planType: Advanced
        price: $120
      subtitle: Find the perfect solution for your wound care needs.
      title: Our Product Range
  site_header:
    component: header
    data:
      containerClasses: max-w-6xl mx-auto
      containerInnerClasses: px-6 py-3
      headerClass: bg-blue-600 text-white shadow-lg rounded-lg mx-auto p-2 my-3
      iconComponent: heroicon-o-medical-bag
      navLinks:
      - label: Products
        url: '#products'
      - label: Solutions
        url: '#solutions'
      - label: Contact Us
        url: '#contact'
      primaryLink: '#get-started'
      siteName: Hydrofera Blue
  solutions_card:
    component: card
    data:
      featureItems:
      - description: Provides reliable protection against bacteria.
        icon: heroicon-o-shield-check
        title: Protection
      - description: Accelerates healing with advanced technology.
        icon: heroicon-o-trending-up
        title: Healing
      - description: Minimizes dressing changes and promotes efficiency.
        icon: heroicon-o-clock
        title: Efficiency
      sectionId: solutions
      sectionTitle: Why Choose Hydrofera Blue?
theme:
  body:
    class: bg-blue-50 text-gray-900
version: 1.0.0
wordpress:
  image_sizes:
    hero_image:
      crop: true
      height: 1080
      width: 1920
  menus:
    primary_navigation:
      location: primary_navigation
      name: Primary Navigation
  theme_support:
  - title-tag
  - post-thumbnails
  - menus
