ascii_art:
  default: |
    ${green}                    &
                          && & &
                      & &&&&&&~&&&
                       &&  &&&&  &&
                        &&&~|\&&&
                         &//~\\&
                        |/    \|
                       /|\    /|\
             &&       |//~    ~\\|
               &&    \_/        \_/  && & &
        &&&    &&     //_/____\\_\  /&&&/_&&&
         &&&__&&   \_\_\/~~~~\/\_/   &&&
       & &\&  &&&&\|&  /~||~\  &|     &
        &&& & &    /~~
                 ${brown}:____________./~~~\.____:
                  \                         /
                   \_____________________/
                   (_)               (_)${reset}

components:
  - hero
  - header
  - card
  - widget
  - pricing-box

sections:
  site_header:
    component: header
    data:
      siteName: "Hydrofera Blue"
      iconComponent: "heroicon-o-beaker"
      navLinks: [
        {"url": "#products", "label": "Products"},
        {"url": "#clinical", "label": "Clinical Evidence"},
        {"url": "#resources", "label": "Resources"},
        {"url": "#contact", "label": "Contact"}
      ]
      primaryLink: "https://hydrofera.com/products"
      containerClasses: "max-w-7xl mx-auto"
      containerInnerClasses: "px-4 sm:px-6 lg:px-8"
      headerClass: "bg-white/80 backdrop-blur-md border-b border-blue-100"
  
  home_hero:
    component: hero
    data:
      title: "Advanced Wound Care"
      subtitle: "Powered by Hydrofera Blue Technology"
      description: "Clinically proven antimicrobial dressings that promote healing and prevent infection in chronic and acute wounds."
      imagePaths: "https://placehold.co/1200x600/png"
      buttonText: "View Products"
      buttonLink: "#products"
      secondaryText: "Clinical Studies"
      secondaryLink: "#evidence"
      buttonLinkIcon: true
      secondaryIcon: true
      iconMappings:
        dropdownIcon: "heroicon-o-chevron-down"
        buttonLinkIcon: "heroicon-o-arrow-right"
        secondaryIcon: "heroicon-o-academic-cap"
  
  features_card:
    component: card
    data:
      title: "Why Hydrofera Blue"
      subtitle: "Advanced Wound Care Technology"
      features: [
        {
          "icon": "heroicon-o-beaker",
          "title": "Proprietary Technology",
          "description": "Unique PVA foam with methylene blue and gentian violet"
        },
        {
          "icon": "heroicon-o-shield-check",
          "title": "Broad-Spectrum Protection",
          "description": "Effective against bacteria, including antibiotic-resistant strains"
        },
        {
          "icon": "heroicon-o-heart",
          "title": "Patient-Friendly",
          "description": "Non-cytotoxic, non-staining, and easy to apply"
        }
      ]
      featureItems: [
        {
          "icon": "heroicon-o-check-circle",
          "title": "Clinically Proven",
          "description": "Extensive research backing efficacy"
        },
        {
          "icon": "heroicon-o-clock",
          "title": "Long-Lasting",
          "description": "Extended wear time up to 7 days"
        },
        {
          "icon": "heroicon-o-currency-dollar",
          "title": "Cost-Effective",
          "description": "Reduces overall treatment costs"
        },
        {
          "icon": "heroicon-o-sparkles",
          "title": "Non-Adherent",
          "description": "Minimizes trauma during dressing changes"
        },
        {
          "icon": "heroicon-o-chart-bar",
          "title": "Proven Results",
          "description": "Demonstrated healing outcomes"
        },
        {
          "icon": "heroicon-o-globe-americas",
          "title": "Worldwide Trust",
          "description": "Used in healthcare facilities globally"
        }
      ]

  clinical_widget:
    component: widget
    data:
      items:
        - id: "evidence-1"
          title: "Clinical Evidence"
          icon: "heroicon-o-academic-cap"
          content: ""
          cta:
            title: "Research Studies"
            link: "#studies"
            imagePath: "https://placehold.co/600x400/png"
          description: "Proven effectiveness in wound care:"
          listItems:
            - number: 1
              itemName: "Clinical Trials"
              text: "Multiple randomized controlled studies"
            - number: 2
              itemName: "Case Studies"
              text: "Documented success across wound types"
            - number: 3
              itemName: "Publications"
              text: "Peer-reviewed journal articles"

  pricing:
    component: pricing
    data:
      title: "Product Range"
      subtitle: "Advanced Wound Care Solutions"
      description: "Choose the right Hydrofera Blue product for your wound care needs"
      pricingBoxes:
        - icon: "heroicon-o-bandage"
          iconColor: "text-blue-600"
          planType: "Classic"
          price: "Contact for Pricing"
          features: [
            "Standard wound care",
            "Broad-spectrum antimicrobial",
            "Up to 7-day wear time",
            "Non-adherent surface",
            "Various sizes available"
          ]
          ctaLink: "#contact-sales"
          ctaText: "Request Info"
          ctaColor: "bg-blue-600"
          iconBtn: "heroicon-o-envelope"
          iconBtnColor: "text-white"
        
        - icon: "heroicon-o-sparkles"
          iconColor: "text-indigo-600"
          planType: "Ready"
          price: "Contact for Pricing"
          features: [
            "No-rinse wound cleanser",
            "Ready to use format",
            "Preservative-free",
            "Gentle application",
            "Compatible with all dressings",
            "Available in multiple sizes"
          ]
          ctaLink: "#contact-sales"
          ctaText: "Request Info"
          ctaColor: "bg-gradient-to-r from-blue-600 to-indigo-600"
          iconBtn: "heroicon-o-envelope"
          iconBtnColor: "text-white"
        
        - icon: "heroicon-o-star"
          iconColor: "text-purple-600"
          planType: "XTRA"
          price: "Contact for Pricing"
          features: [
            "Maximum absorption",
            "Enhanced bacterial binding",
            "Ideal for heavy exudate",
            "Extended wear time",
            "Larger sizes available",
            "Cost-effective solution",
            "Reduced dressing changes"
          ]
          ctaLink: "#contact-sales"
          ctaText: "Request Info"
          ctaColor: "bg-gradient-to-r from-indigo-600 to-purple-600"
          iconBtn: "heroicon-o-envelope"
          iconBtnColor: "text-white"

layouts:
  hydrofera:
    sections:
      - site_header
      - home_hero
      - features_card
      - clinical_widget
      - pricing

pages:
  home:
    title: "Hydrofera Blue - Advanced Wound Care Solutions"
    layout: hydrofera
    is_homepage: true
    meta:
      description: "Discover Hydrofera Blue's advanced antimicrobial wound care solutions. Clinically proven technology for better healing outcomes."

wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    
  image_sizes:
    hero_image:
      width: 1920
      height: 1080
      crop: true
    product_image:
      width: 800
      height: 600
      crop: true

assets:
  styles:
    - resources/styles/hydrofera.scss
  scripts:
    - resources/scripts/hydrofera.js
