name: "CoWork & Create"
description: "A modern co-working space with dedicated podcast and live-streaming rooms."

components:
  - hero
  - cta
  - faq
  - card-featured
  - slideshow

sections:
  home_hero:
    component: hero
    data:
      title: "Welcome to CoWork & Create"
      subtitle: "Your Space to Work, Record, and Innovate"
      description: "State-of-the-art co-working spaces, private podcast booths, and live-streaming studios."
      imagePath: "images/hero-cowork.jpg"
      styles:
        background: "bg-cover bg-center bg-gradient-to-b from-gray-900 via-gray-800 to-gray-700"
        text: "text-white text-5xl font-bold"
      primaryButton:
        text: "Book a Tour"
        link: "/tour"
      secondaryButton:
        text: "Learn More"
        link: "/about"

  features:
    component: card-featured
    data:
      cards:
        - title: "Private Podcast Booths"
          description: "Soundproofed spaces equipped with professional audio equipment."
          image: "images/features-podcast.jpg"
          styles:
            card: "border rounded-lg shadow-lg"
            text: "text-lg font-medium"
        - title: "Live Streaming Studios"
          description: "Stream with professional-grade cameras and lighting."
          image: "images/features-streaming.jpg"
          styles:
            card: "border rounded-lg shadow-lg"
            text: "text-lg font-medium"
        - title: "Modern Workspaces"
          description: "Collaborative and private spaces designed for productivity."
          image: "images/features-workspace.jpg"
          styles:
            card: "border rounded-lg shadow-lg"
            text: "text-lg font-medium"

  faq:
    component: faq
    data:
      questions:
        - question: "Do I need to bring my own equipment?"
          answer: "Our studios are fully equipped, but you are welcome to bring your own gear."
        - question: "Can I book a room for multiple days?"
          answer: "Yes! We offer flexible booking options for daily and long-term rentals."
        - question: "Are there any membership plans?"
          answer: "We have affordable plans for individuals and teams."
      styles:
        container: "bg-gray-100 p-6 rounded-lg shadow-md"
        text: "text-gray-800"

  cta_booking:
    component: cta
    data:
      title: "Ready to Create?"
      subtitle: "Book your space today and turn your ideas into reality."
      buttonPrimary:
        text: "Reserve Now"
        link: "/book"
      styles:
        background: "bg-blue-600"
        text: "text-white text-center font-bold"

  testimonials:
    component: slideshow
    data:
      slides:
        - content: "The podcast booths are amazing—professional quality and great atmosphere!"
          author: "Alex D."
          image: "images/testimonial-alex.jpg"
        - content: "I love the community here. It's inspiring to work alongside other creators."
          author: "Jamie L."
          image: "images/testimonial-jamie.jpg"
      styles:
        container: "bg-gray-50 p-8 rounded-md shadow-lg"
        text: "text-gray-800 text-lg"

layouts:
  homepage:
    sections:
      - home_hero
      - features
      - testimonials
      - faq
      - cta_booking

pages:
  home:
    title: "Home"
    layout: homepage
