name: Roots Ecosystem
description: Modern WordPress development tools and frameworks
version: 0.0.1

ascii_art:
  default: |
    ${green}                    &
                          && & &
                        & &&&&&~&
                         &  &&&&
                          &&&~|\
                           &//~
                          |/
                         /|\
               &&       |//~
                 &&    \_/     && & &
          &&&    &&     //_/  /&&&/_&&&
           &&&__&&   \_\_\/~/   &&&
         & &\&  &&&&\|&  /~|     &
          &&& & &    /~~
                   ${brown}:___________./~~~\.___:
                    \                     /
                     \_________________/
                     (_)           (_)${reset}

components:
  - hero
  - header
  - card
  - widget
  - pricing-box

sections:
  site_header:
    component: header
    data:
      siteName: "Roots"
      iconComponent: "heroicon-o-cube-transparent"
      navLinks: [
        {"url": "#products", "label": "Products"},
        {"url": "#docs", "label": "Documentation"},
        {"url": "#community", "label": "Community"}
      ]
      primaryLink: "https://roots.io"
      containerClasses: "max-w-5xl mx-auto"
      containerInnerClasses: "px-6"
  
  home_hero:
    component: hero
    data:
      title: "Roots Ecosystem"
      subtitle: "Modern WordPress Development"
      description: "Professional tools for modern WordPress development. Build better themes with Sage, manage dependencies with Bedrock, and deploy with Trellis."
      imagePaths: ["https://roots.io/img/roots-dashboard.png"]
      buttonText: "Get Started"
      buttonLink: "#products"
      secondaryText: "Join Community"
      secondaryLink: "https://discourse.roots.io"
      buttonLinkIcon: true
      secondaryIcon: true
      iconMappings:
        dropdownIcon: "heroicon-s-chevron-down"
        buttonLinkIcon: "heroicon-s-arrow-right"
        secondaryIcon: "heroicon-s-users"
  
  services_card:
    component: card
    data:
      sectionId: "products"
      sectionTitle: "Our Products"
      navLinks: [
        {"url": "#docs", "label": "Documentation"},
        {"url": "#community", "label": "Community"}
      ]
      featureItems: [
        {
          "icon": "heroicon-o-template",
          "title": "Sage",
          "description": "WordPress starter theme with modern development tools, easier configuration, and an improved developer experience."
        },
        {
          "icon": "heroicon-o-cube",
          "title": "Bedrock",
          "description": "WordPress boilerplate with modern development tools, easier configuration, and an improved folder structure."
        },
        {
          "icon": "heroicon-o-server",
          "title": "Trellis",
          "description": "WordPress development and production servers done right with Ansible."
        }
      ]

  features_widget:
    component: widget
    data:
      items:
        - id: "widget-1"
          title: "Sage"
          icon: "heroicon-o-template"
          content: ""
          cta:
            title: "Learn More About Sage"
            link: "https://roots.io/sage"
            imagePath: "https://roots.io/img/sage.png"
          description: "Modern WordPress starter theme:"
          listItems:
            - number: 1
              itemName: "Laravel Blade"
              text: "Use Laravel's Blade templating engine in your themes"
            - number: 2
              itemName: "Tailwind CSS"
              text: "Modern utility-first CSS framework included"
            - number: 3
              itemName: "Modern Workflow"
              text: "Webpack, Browsersync, and modern JS features"

        - id: "widget-2"
          title: "Bedrock"
          icon: "heroicon-o-cube"
          content: ""
          cta:
            title: "Learn More About Bedrock"
            link: "https://roots.io/bedrock"
            imagePath: "https://roots.io/img/bedrock.png"
          description: "WordPress boilerplate with security in mind:"
          listItems:
            - number: 1
              itemName: "Composer"
              text: "Manage WordPress and plugin dependencies"
            - number: 2
              itemName: "Environment Files"
              text: "Separate configs for development and production"
            - number: 3
              itemName: "Better Structure"
              text: "Enhanced security through modern folder structure"

        - id: "widget-3"
          title: "Trellis"
          icon: "heroicon-o-server"
          content: ""
          cta:
            title: "Learn More About Trellis"
            link: "https://roots.io/trellis"
            imagePath: "https://roots.io/img/trellis.png"
          description: "One-command WordPress deployment:"
          listItems:
            - number: 1
              itemName: "Development"
              text: "Local development with Vagrant and VirtualBox"
            - number: 2
              itemName: "Production"
              text: "Zero-downtime deploys with Ansible"
            - number: 3
              itemName: "Security"
              text: "SSL, hardened security, and performance tuning"

  pricing:
    component: pricing
    data:
      title: "Choose Your Plan"
      subtitle: "Professional tools for modern WordPress development"
      description: "Join thousands of developers building better WordPress sites with Roots. All plans include access to premium documentation and community support."
      pricingBoxes: [
        {
          "icon": "heroicon-o-code-bracket",
          "iconColor": "text-gray-400",
          "planType": "Individual",
          "price": "$99",
          "features": [
            "All Roots products",
            "Premium documentation",
            "Community support",
            "1 site license"
          ],
          "ctaLink": "https://roots.io/pricing",
          "ctaText": "Get Started",
          "ctaColor": "bg-white",
          "iconBtn": "heroicon-o-arrow-right",
          "iconBtnColor": "text-gray-500"
        },
        {
          "icon": "heroicon-o-building-office",
          "iconColor": "text-gray-500",
          "planType": "Agency",
          "price": "$299",
          "features": [
            "All Individual features",
            "Unlimited site licenses",
            "Priority support",
            "Early access features",
            "Agency training"
          ],
          "ctaLink": "https://roots.io/pricing",
          "ctaText": "Buy Now",
          "ctaColor": "bg-gradient-to-r from-emerald-600 to-green-500 text-white",
          "iconBtn": "heroicon-o-shopping-cart",
          "iconBtnColor": "text-white"
        },
        {
          "icon": "heroicon-o-building-library",
          "iconColor": "text-yellow-500",
          "planType": "Enterprise",
          "price": "Custom",
          "features": [
            "All Agency features",
            "Custom development",
            "Dedicated support",
            "Training workshops",
            "Custom integrations",
            "Architecture review",
            "SLA guarantee"
          ],
          "ctaLink": "https://roots.io/enterprise",
          "ctaText": "Contact Us",
          "ctaColor": "bg-gradient-to-r from-yellow-500 to-amber-500 text-white",
          "iconBtn": "heroicon-o-envelope",
          "iconBtnColor": "text-white"
        }
      ]

layouts:
  roots:
    sections:
      - site_header
      - home_hero
      - services_card
      - features_widget
      - pricing

pages:
  home:
    title: "Roots - Modern WordPress Development Tools"
    layout: roots
    is_homepage: true

wordpress:
  menus:
    primary_navigation:
      location: "primary_navigation"
      name: "Primary Navigation"
  
  theme_support:
    - title-tag
    - post-thumbnails
    - menus
    
  image_sizes:
    hero_image:
      width: 1920
      height: 1080
      crop: true

assets:
  styles:
    - resources/styles/roots.scss
  scripts:
    - resources/scripts/roots.js